-- Oracle Database Schema for Review Pipeline Application

-- Create the REVIEW_QUEUE table
CREATE TABLE REVIEW_QUEUE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_FK VARCHAR2(255) NOT NULL,
    REVIEW_TYPE VARCHAR2(50) NOT NULL,
    REVIEW_MESSAGE VARCHAR2(4000) NOT NULL,
    PROCESSED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PROCESSED_DATE TIMESTAMP,
    CONSTRAINT CHK_PROCESSED CHECK (PROCESSED IN (0, 1))
);

-- Create indexes for performance
CREATE INDEX IDX_REVIEW_QUEUE_CLIENT ON REVIEW_QUEUE(CLIENT_FK, PROCESSED);
CREATE INDEX IDX_REVIEW_QUEUE_PROCESSED ON REVIEW_QUEUE(PROCESSED);
CREATE INDEX IDX_REVIEW_QUEUE_CREATED ON REVIEW_QUEUE(CREATED_DATE);

-- Sample data for testing
INSERT INTO REVIEW_QUEUE (CLIENT_FK, REVIEW_TYPE, REVIEW_MESSAGE, PROCESSED)
VALUES ('CLIENT_001', 'TYPE_A', '{"action": "approve", "amount": 1000}', 0);

INSERT INTO REVIEW_QUEUE (CLIENT_FK, REVIEW_TYPE, REVIEW_MESSAGE, PROCESSED)
VALUES ('CLIENT_001', 'TYPE_B', '{"action": "reject", "reason": "insufficient funds"}', 0);

INSERT INTO REVIEW_QUEUE (CLIENT_FK, REVIEW_TYPE, REVIEW_MESSAGE, PROCESSED)
VALUES ('CLIENT_002', 'DEFAULT', '{"action": "review", "priority": "high"}', 0);

INSERT INTO REVIEW_QUEUE (CLIENT_FK, REVIEW_TYPE, REVIEW_MESSAGE, PROCESSED)
VALUES ('CLIENT_003', 'TYPE_A', '{"action": "approve", "amount": 5000}', 0);

COMMIT;

-- Query to check unprocessed records by client
SELECT CLIENT_FK, COUNT(*) as PENDING_COUNT
FROM REVIEW_QUEUE
WHERE PROCESSED = 0
GROUP BY CLIENT_FK
ORDER BY CLIENT_FK;

-- Query to view all unprocessed records
SELECT *
FROM REVIEW_QUEUE
WHERE PROCESSED = 0
ORDER BY CLIENT_FK, CREATED_DATE;
